In [12]:
from numpy import load

img = load('C:/Users/Kathakoli/Documents/vitmat/vehicle collision/datasets_h5/test_set/1296.npz')
lst = img.files
for item in lst:
    print(item)
    print(img[item])
    print(img[item].shape)

name1
[[[[[ 13  10  22]
    [ 76  50  46]
    [  3   0   9]
    ...
    [175 153 139]
    [175 152 138]
    [175 152 138]]

   [[ 80  54  48]
    [ 19   6  13]
    [  4   3  13]
    ...
    [175 153 139]
    [175 152 138]
    [175 153 139]]

   [[ 65  43  38]
    [  6   3  18]
    [ 48  33  32]
    ...
    [175 152 138]
    [175 152 138]
    [175 152 138]]

   ...

   [[141 136 134]
    [140 135 133]
    [139 134 132]
    ...
    [102  96  94]
    [105 100  98]
    [116 112 109]]

   [[140 135 133]
    [139 134 133]
    [139 135 133]
    ...
    [105 100  98]
    [ 96  90  88]
    [100  94  92]]

   [[140 135 133]
    [140 135 133]
    [140 135 133]
    ...
    [120 115 113]
    [111 106 104]
    [102  97  95]]]


  [[[  7   3  24]
    [ 76  49  45]
    [  0   0  15]
    ...
    [175 152 138]
    [175 152 138]
    [175 152 138]]

   [[ 77  51  45]
    [  9   3  13]
    [  6   3  15]
    ...
    [175 152 139]
    [175 152 138]
    [175 152 138]]

   [[ 64  42  36]
    [ 17  10  20]
    